stilts tmatch2 \
	in1=$1 \
	in2=$2 \
	icmd1='addcol nsi scint_index/(0.06*1.85*pow(sinDeg(elongation),-1.6))' \
	icmd1='addcol err_nsi index_err/(0.06*1.85*pow(sinDeg(elongation),-1.6))' \
	icmd1='keepcols "source_name_tgss ra_tgss dec_tgss elongation nsi err_nsi pbcor"' \
	icmd2='addcol nsi scint_index/(0.06*1.85*pow(sinDeg(elongation),-1.6))' \
	icmd2='addcol err_nsi index_err/(0.06*1.85*pow(sinDeg(elongation),-1.6))' \
	icmd2='keepcols "source_name_tgss ra_tgss dec_tgss elongation nsi err_nsi pbcor"' \
        matcher=Exact \
	join=1or2 \
        values1='source_name_tgss' \
        values2='source_name_tgss' \
	ocmd='replacecol source_name_tgss_1 NULL_source_name_tgss_1?source_name_tgss_2:source_name_tgss_1' \
	ocmd='replacecol ra_tgss_1 NULL_ra_tgss_1?ra_tgss_2:ra_tgss_1' \
	ocmd='replacecol dec_tgss_1 NULL_dec_tgss_1?dec_tgss_2:dec_tgss_1' \
	ocmd='colmeta -name source_name_tgss source_name_tgss_1' \
	ocmd='colmeta -name elongation elongation_1' \
	ocmd='colmeta -name ra_tgss ra_tgss_1' \
	ocmd='colmeta -name dec_tgss dec_tgss_1' \
	ocmd='delcols "source_name_tgss_2 ra_tgss_2 dec_tgss_2 elongation_2"' \
	ocmd='addcol g_ratio nsi_2/nsi_1' \
	ocmd='addcol g_ratio_snr 1/hypot(err_nsi_1/nsi_1,err_nsi_2/nsi_2)' \
	ocmd='clearparams *' \
	ocmd="setparam in1 ${1:0:10}" \
	ocmd="setparam in2 ${2:0:10}" \
	out=$3
